package constant

const (
	REMOTE_PROXY     = "REMOTE_PROXY"
	OPENAI_API_KEY   = "OPENAI_API_KEY"
	CHIMERA_KEY      = "CHIMERA_KEY"
	ERNIE_APP_KEY    = "ERNIE_APP_KEY"
	ERNIE_APP_SECRET = "ERNIE_APP_SECRET"
	NOT_MIRROR       = "NOT_MIRROR"
	FILE_ROOT        = "FILE_ROOT"
	OWNER            = "OWNER"
	BING_COOKIE      = "BING_COOKIE"
)

const (
	DefaultGRPCPort = 9090
)
