package constant

const (
	REMOTE_PROXY   = "REMOTE_PROXY"
	OPENAI_API_KEY = "OPENAI_API_KEY"
	CHIMERA_KEY    = "CHIMERA_KEY"
	NOT_MIRROR     = "NOT_MIRROR"
	FILE_ROOT      = "FILE_ROOT"
	OWNER          = "OWNER"
	BING_COOKIE    = "BING_COOKIE"
)
